version: '3.6'
networks:
  development:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  wheel_db:
    image: postgres:12.5-alpine
    container_name: wheel_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - development
    ports:
      - "5499:5432"
  wheel_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wheel_app
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    entrypoint: docker-entrypoint.sh
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
    depends_on:
      - wheel_db
